Prevent exception due to missing IStartup class when running ButtonTest
If you run ButtonTest from the org.eclipse.e4.ui.tests.css.swt and
include org.eclipse.ui.tests in the run you get an exception because
org.eclipse.ui.tests contains an IStartup extension without class
definition.
This extension was added via Bug 42456 with
23feca4f6b3c48f60775831538dcfa4cd85ef903 but at the same time a correct
IStartup extension was added.

!MESSAGE Unable to execute early startup code for the
org.eclipse.ui.IStartup extension contributed by the
'org.eclipse.ui.tests' plug-in.
!STACK 1
org.eclipse.core.runtime.CoreException: Executable extension definition
for "class" not found.
	at org.eclipse.core.internal.registry.ConfigurationElement.throwException(ConfigurationElement.java:65)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:225)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:281)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2667)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2022-06-09 14:05:33.994
!MESSAGE Executable extension definition for "class" not found.