Revert "Deletes unused DecimalFormat class from core.expressions.tests"
The class is used in tests which fail without it with:
com.ibm.icu.text.DecimalFormat cannot be found by org.eclipse.core.expressions.tests_3.5.800.v20200408-1052

java.lang.ClassNotFoundException: com.ibm.icu.text.DecimalFormat cannot be found by org.eclipse.core.expressions.tests_3.5.800.v20200408-1052
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
at java.lang.ClassLoader.loadClass(C

This reverts commit e124dd152d0e92059808b54e3be8a2b2f7e4360b.

Change-Id: Ieba794f214fd070901848593f7e2081ffe4c0365