Bug 417258 - properly reset ILogger and ISafeRunnableRunner after tests
Few tests were not properly restoring ILogger and ISafeRunnableRunner,
which caused absolutely unrelated tests to fail, like this stack below:

junit.framework.AssertionFailedError: /$nl$/icons/does-not-exist.gif
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at
org.eclipse.jface.tests.viewers.ViewerTestCase$1.log(ViewerTestCase.java:112)
	at org.eclipse.jface.util.Policy.logException(Policy.java:259)
	at
org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:226)
	at
org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:283)
	at
org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
	at
org.eclipse.ui.tests.api.EditorIconTest.testBug395126_missing(EditorIconTest.java:127)

Change-Id: Id4cf2147434476b5cf4fd24561faeaeeae31f839
Signed-off-by: Andrey Loskutov <loskutov@gmx.de>