Fix NullPointerException in LogView
This commit addresses an occasionally occurring NullPointerException in the LogView class:
```
LogListener.logged threw a non-fatal unchecked exception as follows:
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.action.Action.isChecked()" because "this.fActivateViewAction" is null
	at org.eclipse.ui.internal.views.log.LogView.asyncRefreshAndActivate(LogView.java:1253)
	at org.eclipse.ui.internal.views.log.LogView.pushEntry(LogView.java:1212)
	at org.eclipse.ui.internal.views.log.LogView.logged(LogView.java:1143)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:108)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory$LogTask.run(ExtendedLogReaderServiceFactory.java:56)
	at org.eclipse.osgi.internal.log.OrderedExecutor$OrderedTaskQueue$OrderedTask.run(ExtendedLogReaderServiceFactory.java:458)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```