Bug 497330 - [GTK3] Platform.UI test failures on GTK
Improve Bug201002TableViewerTest assert to explicitly state the issue
instead of the cryptic "expected:<true> but was:<false> ".

Change-Id: I29e62dc50263e6f3b48d934745d10a76f177e6b7
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>