Revert "Make webapp use precompiled jsp files."
This reverts commit b023f39e07e0a848dfdc85243cf18b051e1b0a84 as it breaks the help system entirely (http code 500).
Caused by:

java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspSourceImports