Bug 578725 - fix [autobuild] Random startup issues
if subMonitor.split throws OperationCanceledException the
"prepareOperation" was not execuded but "endOperation" which caused
IllegalArgumentException: endRule without matching beginRule

Change-Id: I03eb712f766f3129272bef86ab8fb59a054a85eb
Signed-off-by: Joerg Kubitz <jkubitz-eclipse@gmx.de>
Reviewed-on: https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/190761
Tested-by: Andrey Loskutov <loskutov@gmx.de>
Reviewed-by: Andrey Loskutov <loskutov@gmx.de>